pool:
  vmImage: 'Ubuntu 16.04'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '11.x'

- script: git submodule update --remote --merge ImageMagick
  displayName: git submodule update

- script: npm install
  displayName: install and build

- script: npm test
  displayName: test

- script: cp magick* $(Build.ArtifactStagingDirectory)
  displayName: cp magick files to artifact staging directory
  
- task: PublishBuildArtifacts@1
  continueOnError: true
  inputs:
    artifactName: 'magick' 
