pool:
  vmImage: 'Ubuntu 16.04'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '8.x'

- script: |
   echo "node version `node -v`"
   echo "npm version `npm -v`" 
   npm install
  displayName: npm install

- script: |
   echo "node version `node -v`"
   echo "npm version `npm -v`" 
   npm test
  displayName: run tests

- script: cp magick* $(Build.ArtifactStagingDirectory)
  displayName: cp magick files to artifact staging directory
  
- task: PublishBuildArtifacts@1
  continueOnError: true
  inputs:
    artifactName: 'magick' 
